environment-defaults:
  perks-production:
    branch: master
    repository: null
  perks-staging:
    branch: master
    repository: null
global:
  application_name: Prizy-V2
  default_ec2_keyname: deploy-v2
  default_platform: 64bit Amazon Linux 2018.03 v2.8.0 running Ruby 2.2 (Puma)
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
