main_category:
  10: Food & Restaurant
  11: Fitness & Health
  12: Fashion & Beauty
  13: Housekeeping & Child Care
  14: Education & Business
  15: Entertainment & Activities
  16: Shopping & Products
  17: Travel & Getaways
