# MySQL.  Versions 5.0+ are recommended.
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: perks
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  <<: *default
  database: perks_test

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
