# MySQL.  Versions 5.0+ are recommended.
default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  pool: 5
  username: root
  password: 123456
  host: 127.0.0.1
  port: 3307
  variables:
    sql_mode: TRADITIONAL

development:
  <<: *default
  database: prizy_development

staging:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  pool: 5
  variables:
    sql_mode: TRADITIONAL
  host:     <%= ENV['DB_HOST'] %>
  port:     <%= ENV['DB_PORT'] || 3306 %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: prizy_staging

production:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>
