ALTER TABLE posts ADD COLUMN privacy TINYINT(2) NOT NULL DEFAULT 0 AFTER description;
ALTER TABLE posts ADD COLUMN post_type TINYINT(2) NOT NULL DEFAULT 0 AFTER privacy;
ALTER TABLE company ADD COLUMN plan_approved TINYINT(2) NOT NULL DEFAULT 0 AFTER plan;
ALTER TABLE company ADD COLUMN bonus_points INT DEFAULT 0 AFTER hashtags;
